-- My Fitness Rev 4: Profile + Weight tracking
create table if not exists public.profiles (
 user_id uuid primary key references auth.users(id) on delete cascade,
 name text not null default '',
 date_of_birth date,
 gender text,
 height_cm numeric(5,1),
 goal text,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
create table if not exists public.weight_entries (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 recorded_at date not null default current_date,
 weight_kg numeric(6,2) not null check(weight_kg>0 and weight_kg<500),
 notes text,
 created_at timestamptz not null default now()
);
create index if not exists idx_weight_entries_user_date on public.weight_entries(user_id,recorded_at desc);
alter table public.profiles enable row level security;
alter table public.weight_entries enable row level security;
drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own on public.profiles for select to authenticated using(auth.uid()=user_id);
drop policy if exists profiles_insert_own on public.profiles;
create policy profiles_insert_own on public.profiles for insert to authenticated with check(auth.uid()=user_id);
drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles for update to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists weight_select_own on public.weight_entries;
create policy weight_select_own on public.weight_entries for select to authenticated using(auth.uid()=user_id);
drop policy if exists weight_insert_own on public.weight_entries;
create policy weight_insert_own on public.weight_entries for insert to authenticated with check(auth.uid()=user_id);
drop policy if exists weight_update_own on public.weight_entries;
create policy weight_update_own on public.weight_entries for update to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists weight_delete_own on public.weight_entries;
create policy weight_delete_own on public.weight_entries for delete to authenticated using(auth.uid()=user_id);
create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();

-- Rev 4.2: two-minute heart-rate recovery
alter table public.cardio_sessions add column if not exists hr_recovery_2min numeric;
